### ISSUE TITLE
Further improve code coverage

### ISSUE THREAD

**Issue by nehcuy** [AY2223S1-CS2103T-W16-3/tp#139]
Projected classes to cover:
- [x] `GetInpatientCommand` Currently: 0%
- [x] `GetOutpatientCommand` Currently: 0%
- [x] `GetMedicationCommand` Currently: 66% methods, 55% lines

Testing under Kartik:
- [x] `GetPastAppointmentCommand` Currently: 66% methods, 31% lines
- [x] `DeletePastAppointmentCommand` Currently: 0%
- [x] `CreatePastAppointmentCommandParser` Currently: 0%
- [x] `DeletePastAppointmentCommandParser` Currently: 0%
- [x] `CountCommand` Currently: 50% methods, 75% lines

**Comment by kxrt** [comment]
I'd like to deal with the PastAppointment-related classes, if that's alright!

**Comment by nehcuy** [comment]
Please feel free to take the classes that you are more comfortable with. I am only including all the test cases that I think we need to do. Also if you think there are more classes that needs to be covered I'll include them as well.
