### ISSUE TITLE
[PE-D][Tester D] Add command example in Command Summary is incorrect

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W16-3/tp#145]
![image.png](https://raw.githubusercontent.com/parth-io/ped/main/files/909777bf-8e72-499c-b02b-d1db7b9cc9a1.png)
 
The `add` command example in the command summary does not work as the ward number is incorrect.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: parth-io/ped#1

**Comment by nehcuy** [comment]
This issue was already resolved in a previous PR.
