### ISSUE TITLE
[PE-D][Tester D] Enumeration of features is not hyperlinked

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W16-3/tp#180]
It seems that the table listing the features in the User Guide, as shown in the screenshot below, is meant to be hyperlinked but it is not.

![image.png](https://raw.githubusercontent.com/parth-io/ped/main/files/5753d009-9588-42ce-97f2-edc553b930f7.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: parth-io/ped#10

**Comment by Charles1026** [comment]
This issue has been fixed in the above PR, the hyperlinks have been added to improve navigability.
